/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useEffect, type JSX } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import * as THREE from 'three'

type GLTFResult = {
  nodes: {
    FernandoTheFlamingo: THREE.SkinnedMesh
    Body: THREE.Bone
    FootL: THREE.Bone
    FootR: THREE.Bone
    neutral_bone: THREE.Bone
  }
  materials: {
    Atlas: THREE.MeshStandardMaterial
  }
}

type ModelProps = JSX.IntrinsicElements['group'] & {
  animation?: string;
}

export function Model({ animation = 'Idle', ...props }: ModelProps) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/Characters/GLTF/Mech_FernandoTheFlamingo.glb') as unknown as GLTFResult & { animations: THREE.AnimationClip[] }
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    const action = actions[animation];
    if (action) {
      action.reset().fadeIn(0.24);
      
      // Don't loop Jump animation - pause at end
      if (animation === 'Jump') {
        action.setLoop(THREE.LoopOnce, 1);
        action.clampWhenFinished = true;
      } else {
        action.setLoop(THREE.LoopRepeat, Infinity);
      }
      
      action.play();
    }
    
    return () => {
      actions?.[animation]?.fadeOut(0.24);
    };
  }, [animation, actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="RobotArmature">
          <skinnedMesh
            name="FernandoTheFlamingo"
            geometry={nodes.FernandoTheFlamingo.geometry}
            material={materials.Atlas}
            skeleton={nodes.FernandoTheFlamingo.skeleton}
            castShadow
            receiveShadow
          />
          <primitive object={nodes.Body} />
          <primitive object={nodes.FootL} />
          <primitive object={nodes.FootR} />
          <primitive object={nodes.neutral_bone} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Characters/GLTF/Mech_FernandoTheFlamingo.glb')
